name: Create Draft Release
on:
  workflow_call:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Action create-draft-release
        id: create-draft-release
        uses: okdyy75/dev-reusable-workflow/.github/actions/create-draft-release@main
